ServerSettings:
  bindAddr: '0.0.0.0:8001'
  readTimeout: '1'
  writeTimeout: '1'
  idleTimeout: '5'

Authentication:
  jwtSecretToken: 'secret'

Session:
  sessionKey: 'QukKcWJ3BNJ70LIIzcB6yqEi/1qFzPq8MdOZCGPziWc='